---
- name: Launch VM on GCP
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    gcp_project: "qwiklabs-gcp-02-6ab56494f7c6"
    gcp_region: "us-east1"
    gcp_zone: "us-east1-b"
    gcp_credentials_file: "{{ lookup('env', 'GCP_SA_KEY') }}"
    vm_name: "rucha-ansible-vm"

  tasks:

    - name: Create GCP VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ vm_name }}"
        machine_type: "e2-medium"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_credentials_file }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "projects/debian-cloud/global/images/family/debian-12"
        network_interfaces:
          - network: "default"
        state: present

      register: vm_output

    - debug:
        msg: "VM created successfully: {{ vm_output.target_link }}"
