---
- name: Launch GCP Instance via Jenkins
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    gcp_project: "qwiklabs-gcp-00-ea09ed000360"
    gcp_region: "us-east1"                       # Only region, no specific zone
    machine_type: "e2-medium"
    instance_name: "rucha-jenkins-ansible-vm"
    gcp_cred_file: "{{ lookup('env', 'GCP_KEY') }}"  # Env variable for Jenkins secret

  tasks:
    - name: Verify GCP key file
      debug:
        msg: "GCP key file path is {{ gcp_cred_file }}"

    - name: Create a GCP instance
      google.cloud.gcp_compute_instance:
        name: "{{ instance_name }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: projects/debian-cloud/global/images/family/debian-11
        network_interfaces:
          - network:
              selfLink: "global/networks/default"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_cred_file }}"
        region: "{{ gcp_region }}"       # Use region instead of zone
        state: present
      register: instance_data

    - name: Display Public IP
      debug:
        msg: "Instance Created. Public IP: {{ instance_data.networkInterfaces[0].accessConfigs[0].natIP }}"
